<div class="block-offer-upgrade">
    <p>
        <?php esc_html_e('Upgrade to the ', PRICE_BY_ROLE_LITE_LANGUAGE_DOMAIN); ?>
        <strong>
            <?php esc_html_e('PREMIUM VERSION ', PRICE_BY_ROLE_LITE_LANGUAGE_DOMAIN); ?>
        </strong>
        <?php esc_html_e('of ', PRICE_BY_ROLE_LITE_LANGUAGE_DOMAIN); ?>
        <strong>
            <?php esc_html_e('PRICE BY USER ROLE ', PRICE_BY_ROLE_LITE_LANGUAGE_DOMAIN); ?>
        </strong>
        <?php esc_html_e('to benefit from all features and official support!', PRICE_BY_ROLE_LITE_LANGUAGE_DOMAIN); ?>
    </p>
    <a href="<?php echo esc_url(PRICE_BY_ROLE_LITE_PREMIUM_VERSION_URL); ?>" target="_blank">
        <button class="button-primary">
            <?php esc_html_e("Upgrade to the premium version", PRICE_BY_ROLE_LITE_LANGUAGE_DOMAIN); ?>
        </button>
    </a>
</div>